/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.convercao;

/**
 *
 * @author Aluno
 */
public class Conversor extends javax.swing.JFrame {

    /**
     * Creates new form Conversor
     */
    public Conversor() {
        initComponents();
    }
    
    double valor;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campotexto = new javax.swing.JTextField();
        boxprimario = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        boxsecundario = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtResultado = new javax.swing.JLabel();
        Reset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        campotexto.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        campotexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campotextoActionPerformed(evt);
            }
        });

        boxprimario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar", "Quilometros", "Metros", "Decimetros", "Centimetros", "Milimetros" }));
        boxprimario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxprimarioActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Converter para:");

        boxsecundario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar", "Kilometros", "Metros", "Decimetros", "Centimetros", "Milimetros" }));

        jButton1.setText("Converter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Resultado:");

        txtResultado.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(campotexto)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(boxsecundario, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(boxprimario, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Reset)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(campotexto, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(boxprimario, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boxsecundario, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boxprimarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxprimarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxprimarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        valor = Double.parseDouble(campotexto.getText());
        if(boxprimario.getSelectedItem().equals("Quilometros") && boxsecundario.getSelectedItem().equals("Metros")){
            txtResultado.setText(String.valueOf(valor*1000+" m"));
        }else if(boxprimario.getSelectedItem().equals("Quilometros") && boxsecundario.getSelectedItem().equals("Decimetros")){
            txtResultado.setText(String.valueOf(valor*10000+" dm"));
        }else if(boxprimario.getSelectedItem().equals("Quilometros") && boxsecundario.getSelectedItem().equals("Centimetros")){
            txtResultado.setText(String.valueOf(valor*100000+" cm"));
        }else if(boxprimario.getSelectedItem().equals("Quilometros") && boxsecundario.getSelectedItem().equals("Milimetros")){
            txtResultado.setText(String.valueOf(valor*1000000+" mm"));
        }else if(boxprimario.getSelectedItem().equals("Quilometros") && boxsecundario.getSelectedItem().equals("Kilometros")){
            txtResultado.setText(String.valueOf(valor*1+" km"));
            
        }else if(boxprimario.getSelectedItem().equals("Metros") && boxsecundario.getSelectedItem().equals("Quilometros")){
            txtResultado.setText(String.valueOf(valor/1000+" km"));
        }else if(boxprimario.getSelectedItem().equals("Metros") && boxsecundario.getSelectedItem().equals("Decimetros")){
            txtResultado.setText(String.valueOf(valor*10+" dm"));
        }else if(boxprimario.getSelectedItem().equals("Metros") && boxsecundario.getSelectedItem().equals("Centimetros")){
            txtResultado.setText(String.valueOf(valor*100+" cm"));
        }else if(boxprimario.getSelectedItem().equals("Metros") && boxsecundario.getSelectedItem().equals("Milimetros")){
            txtResultado.setText(String.valueOf(valor*1000+" mm"));
        }else if(boxprimario.getSelectedItem().equals("Metros") && boxsecundario.getSelectedItem().equals("Metros")){
            txtResultado.setText(String.valueOf(valor*1+" m"));
            
        }else if(boxprimario.getSelectedItem().equals("Decimetros") && boxsecundario.getSelectedItem().equals("Quilometros")){
            txtResultado.setText(String.valueOf(valor/10000+" km"));
        }else if(boxprimario.getSelectedItem().equals("Decimetros") && boxsecundario.getSelectedItem().equals("Metros")){
            txtResultado.setText(String.valueOf(valor/10+" m"));
        }else if(boxprimario.getSelectedItem().equals("Decimetros") && boxsecundario.getSelectedItem().equals("Centimetros")){
            txtResultado.setText(String.valueOf(valor*10+" cm"));
        }else if(boxprimario.getSelectedItem().equals("Decimetros") && boxsecundario.getSelectedItem().equals("Milimetros")){
            txtResultado.setText(String.valueOf(valor*100+" mm"));
        }else if(boxprimario.getSelectedItem().equals("Decimetros") && boxsecundario.getSelectedItem().equals("Decimetros")){
            txtResultado.setText(String.valueOf(valor*1+" dm"));
            
        }else if(boxprimario.getSelectedItem().equals("Centimetros") && boxsecundario.getSelectedItem().equals("Quilometros")){
            txtResultado.setText(String.valueOf(valor/100000+" km"));
        }else if(boxprimario.getSelectedItem().equals("Centimetros") && boxsecundario.getSelectedItem().equals("Metros")){
            txtResultado.setText(String.valueOf(valor/100+" m"));
        }else if(boxprimario.getSelectedItem().equals("Centimetros") && boxsecundario.getSelectedItem().equals("Decimetros")){
            txtResultado.setText(String.valueOf(valor/10+" dm"));
        }else if(boxprimario.getSelectedItem().equals("Centimetros") && boxsecundario.getSelectedItem().equals("Milimetros")){
            txtResultado.setText(String.valueOf(valor*10+" mm"));
        }else if(boxprimario.getSelectedItem().equals("Centimetros") && boxsecundario.getSelectedItem().equals("Centimetros")){
            txtResultado.setText(String.valueOf(valor*1+" cm"));
            
        }else if(boxprimario.getSelectedItem().equals("Milimetros") && boxsecundario.getSelectedItem().equals("Quilometros")){
            txtResultado.setText(String.valueOf(valor/1000000+" km"));
        }else if(boxprimario.getSelectedItem().equals("Milimetros") && boxsecundario.getSelectedItem().equals("Metros")){
            txtResultado.setText(String.valueOf(valor/1000+" m"));
        }else if(boxprimario.getSelectedItem().equals("Milimetros") && boxsecundario.getSelectedItem().equals("Decimetros")){
            txtResultado.setText(String.valueOf(valor/100+" dm"));
        }else if(boxprimario.getSelectedItem().equals("Milimetros") && boxsecundario.getSelectedItem().equals("Centimetros")){
            txtResultado.setText(String.valueOf(valor/10+" cm"));
        }else if(boxprimario.getSelectedItem().equals("Milimetros") && boxsecundario.getSelectedItem().equals("Centimetros")){
            txtResultado.setText(String.valueOf(valor*1+" mm"));
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void campotextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campotextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campotextoActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
        txtResultado.setText("");
        campotexto.setText("");
        boxprimario.setSelectedIndex(0);
        boxsecundario.setSelectedIndex(0);
    }//GEN-LAST:event_ResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Conversor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Reset;
    private javax.swing.JComboBox<String> boxprimario;
    private javax.swing.JComboBox<String> boxsecundario;
    private javax.swing.JTextField campotexto;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel txtResultado;
    // End of variables declaration//GEN-END:variables
}
